### PR TITLE
Version 1.1

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by 304NotModified** [comment]
works, now cleanup

**Comment by 304NotModified** [comment]
Unfortunately, I can't get it working that the package version of the csproj is used.

Also AppVeyor is patching to much without asking (e.g. assemblyversion if not set) - really annoying

**Comment by snakefoot** [comment]
Why not just include the AppVeyor build-number in the csproj, and just remove the patching completely from AppVeyor ?

**Comment by 304NotModified** [comment]
Yes, maybe that was better. I was hoping that the patching was working smoother.

**Comment by snakefoot** [comment]
Yes current released version has file-version `1.0.0.35` and assembly-version `1.1.0.0`.

If my testing succeeds then I better keep assembly-version at `1.1.0.0` :)

**Comment by 304NotModified** [comment]
The assembly version is 1.0.0.0? (and that's good)

image

The file version should be increasing. 1.0.0.35 is good for that.

**Comment by snakefoot** [comment]
Yes you are right. Just me being blind. Thanks for the glasses.

**Comment by 304NotModified** [comment]
NP

I was shocked as I double checked it :)

**Pull request merged**
